spring:
  datasource:
    druid:
      url: jdbc:mysql://47.98.117.137:33897/springcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: user02
      password: Ridilong@2019
      stat-view-servlet:
        login-username: admin
        login-password: admin
